name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches:
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: Hajuha
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Saigon

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: "${{ secrets.LAST_FM_API_KEY }}}"
          plugin_music_mode: recent
          plugin_music_limit: 4
